export const shopCategories = [
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
    {value: "clothing", label: "Clothing & Apparel"},
]