export const shopCategories = [
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'clothing', label: 'Clothing & Apparel' },
  { value: 'fitness', label: 'Clothing & Apparel' },
  { value: 'real_estate', label: 'Real Estate & Property Services' },
  { value: 'clothing', label: 'Fitness & Wellness Centers' },
  { value: 'entertainment', label: 'Entertainment & Gaming' },
  { value: 'other', label: 'Other' },
];
