import '../../../../packages/theme/fonts.css';
import './global.css';
import Providers from './provider';

export const metadata = {
  title: 'Eshop - Admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-slate-900 antialiased font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
